name: update-action-image

inputs:
  action_image:
    description: Docker image reference to write into action.yml
    required: true

runs:
  using: composite
  steps:
    - name: Update action.yml image reference
      shell: bash
      env:
        ACTION_IMAGE: ${{ inputs.action_image }}
      run: |
        yq e '.runs.image = env(ACTION_IMAGE)' -i action.yml
