name: build-and-deploy-image

inputs:
  registry:
    description: The registry to deploy to
    required: true
  image_name:
    description: The name of the docker image
    required: true
  username:
    description: The username to login to the container registry
    required: true
  password:
    description: The password to login to the container registry
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: type=sha,format=long

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Commit changes
      shell: bash
      env:
        IMAGE_TAG: docker://${{ steps.meta.outputs.tags }}
      run: |
        git config --global user.name 'Github'
        git config --global user.email 'github@users.noreply.github.com'

        yq e ".runs.image = env(IMAGE_TAG)" -i action.yml
        git add action.yml
        git diff-index --quiet HEAD || (git commit -m "[Auto] Image tag updated latest pushed version" && git push)